theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
header_pages:
  - csmap_url_historian.md
  - csmap_privacy_policy.md
  - url_historian_help.md
header_pages_es:
  - csmap_url_historian_es.md
  - csmap_privacy_policy_es.md
  - url_historian_ayuda.md
include:
  - README.md
  - index.md
  - csmap_url_historian.md
  - csmap_testing_instructions.md
  - csmap_url_historian_es.md
  - csmap_privacy_policy.md
  - survey_instructions_pt3.md
  - survey_instructions_pt4.md
  - survey_instructions_pt5.md
author: "NYU's Center for Social Media and Politics"
